server:
  port: 8081
spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/jixing
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jixing.cms.model
  configuration.map-underscore-to-camel-case: true