server:
  port: 8081
spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/jixing?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jixing.cms.model
  configuration.map-underscore-to-camel-case: true
uploadPath: D:\javas\sources\
serverUrl: https://106.52.26.157/